add_newline = true

[battery]
charging_symbol = "⇡"
disabled = false
discharging_symbol = "⇣"
format = "[$symbol$percentage ]($style)"
full_symbol = ""

[[battery.display]]
style = "red"
threshold = 10

[[battery.display]]
style = "yellow"
threshold = 30

[[battery.display]]
style = "white"
threshold = 89

[[battery.display]]
style = "green"
threshold = 90

[character]
symbol = "$symbol "
use_symbol_for_status = true

[cmd_duration]
format = "took [$duration]($style)"
min_time = 0

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true

[hostname]
disabled = false
ssh_only = false

[line_break]
disabled = false

[username]
disabled = false
show_always = true
